FROM node:18-alpine

# Set environment variable here
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
RUN echo "Use env variable for API base URL: {$REACT_APP_API_BASE_URL}"

WORKDIR /app

COPY ./app .
RUN npm install

EXPOSE 80 

CMD ["npm", "start"]
