services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_BASE_URL: http://localhost:8000
    ports:
      - "8080:3000"
    volumes:
      - ./frontend/app:/app # Mount source code for hot-reloading
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
